export const SET_ROUND_STATUS = 'SET_ROUND_STATUS';
export const ADD_ROUND_QUESTION = 'ADD_ROUND_QUESTION';
export const RESET_ROUND = 'RESET_ROUND';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const ADD_ROUND_POINTS = 'ADD_ROUND_POINTS';
export const CLEAR_ROUND = 'CLEAR_ROUND';
